### ISSUE TITLE
Import tracks in reverse order

### ISSUE THREAD

**Issue by sanchewy** [sigma67/spotify_to_ytmusic#109]
I noticed after a mass `spotify_to_ytmusic all` import that all my playlists in the destination (yt music) were ordered with the latest songs from my Spotify playlist but inverted.

i.e. if the spotify playlist was ordered
```
1. Foo
2. Bar
3. Baz
```
the playlist in yt music would be ordered  
```
1. Baz
2. Bar
3. Foo
```

At time of writing ytmusic only allows sorting playlists as newest-first or newest-last. But if I were to add songs to an imported playlist, all the songs prior to the import date (as seen in Spotify) will be inversely sorted to the songs added after the import date.

i.e. if ytmusic playlist from above gets two new songs (in order) "flock" and "fleek" sorting the playlist 'newest-first' will result in
```
1. Fleek   -- Newest New
2. Flock   -- Oldest New
3. Baz     -- Oldest Old
4. Bar
5. Foo.    -- Newest Old
```
while sorting the playlist 'newest-last' will result in 
```
1. Foo      -- Newest Old    
2. Bar
3. Baz      -- Oldest Old
4. Flock    -- Oldest New
5. Fleek    -- Newest New
```

Request: Please add a flag to import the track in desc/asc order

**Comment by sanchewy** [comment]
This already exists, I just didn't see it at first. https://github.com/linsomniac/spotify_to_ytmusic?tab=readme-ov-file#reverse-your-playlists---tab-2

**Comment by sigma67** [comment]
Not sure why you're linking to a different project as the solution
