### ISSUE TITLE
Spotify auth not working

### ISSUE THREAD

**Issue by npaladin2000** [sigma67/spotify_to_ytmusic#67]
I'm getting a continuous loop trying to authenticate with Spotify and the app I created. Using http://localhost for the redirect (http://localhost:8080 as suggested comes back invalid).  Seems to be failing to write the token to the ~/.cache directory

**Comment by Joker-commits** [comment]
Hi, i'm also facing same issue. Meanwhile, i have created my liked songs as a separate playlist (public), selected 'No' for Spotify authorisation during setup and then exported all my playlists to YT music.

**Comment by sigma67** [comment]
Hi guys, this should be fixed as of 0.3.0. Please report back if not or close otherwise

**Comment by npaladin2000** [comment]
I noticed it was actually trying to create a .cache file in the directory it's run from but when I ran it from my home directory it was conflicting with an already existing .cache folder. Had to run it in another folder

**Comment by sigma67** [comment]
yes, that should be fixed now.
