### ISSUE TITLE
Request: Add a way to retry / resume transfers if a failure occurs

### ISSUE THREAD

**Issue by ageisen2000** [sigma67/spotify_to_ytmusic#69]
A failure occurred during a transfer of my liked playlist to youtube music. I am not sure if it's because I'm being rate limited or something else.

There should be a way to resume previously failed transfers.

**Comment by sigma67** [comment]
there is already WIP that enables this, see here: https://github.com/sigma67/spotify_to_ytmusic/pull/53

**Comment by sigma67** [comment]
Duplicate of #39
