### ISSUE TITLE
SpotifyOauthError: Invalid_grant - When trying to update playlist 

### ISSUE THREAD

**Issue by studied-sermon-gender** [sigma67/spotify_to_ytmusic#80]
Hey, whenever I try to update my playlist, I get this error code:
`Getting Spotify tracks...
Could not get Spotify playlist. Please check the playlist link.
 Error: SpotifyOauthError('error: invalid_grant, error_description: Refresh token revoked')
Traceback (most recent call last):
  File "/var/home/frog/.local/bin/spotify_to_ytmusic", line 8, in <module>
    sys.exit(main())
  File "/var/home/frog/.local/lib/python3.10/site-packages/spotify_to_ytmusic/main.py", line 86, in main
    args.func(args)
  File "/var/home/frog/.local/lib/python3.10/site-packages/spotify_to_ytmusic/controllers.py", line 86, in update
    videoIds = ytmusic.search_songs(playlist["tracks"])
TypeError: 'NoneType' object is not subscriptable
`
I already tried to rerun the setup several times and I'm also positive that the playlist link is in fact the correct one. Also already tried it with different playlists too, but that results in the same error message.

**Comment by sigma67** [comment]
There's probably something wrong with your credentials. Please double check your app is set up correctly in the Spotify Dashboard. May also consider recreating it

**Comment by studied-sermon-gender** [comment]
Tried to create a new app in the Spotify Developer dashboard, still doesn't work. Any ideas?
