### ISSUE TITLE
Enhacement idea: Reverse the order of a playlist 

### ISSUE THREAD

**Issue by szotts** [sigma67/spotify_to_ytmusic#87]
I'm looking for a way to reverse the order of the output playlist on YT Music. As my original playlist on Spotify is sorted to show the newest first, they land at the bottom of the transferred playlist on YT Music. Is there a way to add this functionality to the project?

**Comment by sigma67** [comment]
Not sure I understand, the items should appear in the same order they are on Spotify. How can you even sort a playlist on Spotify?

**Comment by szotts** [comment]
Yes you can, there is a button for it inside a playlist. 
![image](https://github.com/sigma67/spotify_to_ytmusic/assets/35969300/0ef3e038-a5f4-4a30-b968-d37097e783a4)

My playlist is sorted by date added descending, but after the transfer, it's sorted by date added ascending.
Sorting by date added on YouTube doesn't work.

**Comment by sigma67** [comment]
Sorry, I would rather not add a workaround for a feature that does not exist in YouTube Music. Especially since reversing the playlist is only a crude proxy to what you actually want.

If you need this you can always save the sorted spotify playlist as a new playlist with that order?
