### ISSUE TITLE
[Feature Request] Like Songs in YouTube music

### ISSUE THREAD

**Issue by MuhammadBayiz** [sigma67/spotify_to_ytmusic#94]
Option for adding imported songs from Spotify to be added to "Liked Music" playlist of YouTube music instead of "Liked Music (Spotify)". Meaning like songs as they getting imported. All this with the `spotify_to_ytmusic liked` option.

**Comment by sigma67** [comment]
see #38

**Comment by MuhammadBayiz** [comment]
I've seen that PR but how come it isn't implemented in the main repo yet?

**Comment by Tim-Odermatt** [comment]
Any updates to the question from @MuhammadBayiz ?

**Comment by sigma67** [comment]
Sure can be merged, just needs some conflicts to be resolved. Feel free to merge/resubmit
