### ISSUE TITLE
OAuth setup question potentially does not have any input checking

### ISSUE THREAD

**Issue by alexmdev04** [sigma67/spotify_to_ytmusic#96]
During setup, when asked
`Use OAuth method for authorization to transfer private playlists (yes/no):`
If you respond with anything other than `yes` or `no` (e.g. `y`) it will accept the answer but will always error with 
`ValueError: Not a boolean: y`

**Comment by sigma67** [comment]
Yes. It states what you're supposed to answer. Are you surprised you're getting an error if you answer something different?

**Comment by alexmdev04** [comment]
Okay there's no need to be rude I'm just pointing out that users usually expect a level of input sanitation to prevent this kind of thing from happening, clearly you aren't interested in doing this which is completely fine for a small single purpose free tool, however if you ever develop anything with a broader user base I would recommend using input sanitation to prevent complaints and save yourself the headache of dealing with users. 👍

**Comment by sigma67** [comment]
I didn't write that code, it's by @webns 

I also didn't say I'm not open to changing it. Feel free to submit a PR
